In [1]:
import numpy as np

# 1. Determinant

In [2]:
A = np.array([[1,2],[3,4]])
determinant = np.linalg.det(A)
determinant

-2.0000000000000004

In [3]:
B = np.array([[1,2,3], [4,5,6], [7,8,9]])
determinant = np.linalg.det(B)
determinant

6.66133814775094e-16

# 2. Transpose

In [4]:
Transpose = np.transpose(B)
Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
C = np.array([[1,2,3],[4,5,6]])
Transpose = np.transpose(C)
Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

# 3. Inverse

In [8]:
A = np.array([[1,2],[3,4]])
Inverse = np.linalg.inv(A)
Inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])