In [1]:
import numpy as np

In [12]:
arr = np.array([[[1,2,3],[4,5,6],[1,3,5]], [[7,8,9],[10,11,12],[4,5,3]], [[7,8,9],[10,11,12],[4,5,3]]])
print(arr)
print('-'*10)

# Access a specific Element
print(arr[0][1][2])
print(arr[0,1,2])
print('-'*10)

# Access a specific row
print(arr[0])
print(arr[0,:])
print(arr[0,:,:])
print(arr[:,0,:])
print(arr[:,:,0])
print('-'*10)

# Access with specific case
print(arr[[1,2], : , :])
print(arr[[1,2], : , 1])
print('-'*10)

# Access with specific conditions
print(arr[arr>5])
arr[arr >= 18] = "True"
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  3  5]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]
----------
6
6
----------
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [7 8 9]
 [7 8 9]]
[[ 1  4  1]
 [ 7 10  4]
 [ 7 10  4]]
----------
[[[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]
[[ 8 11  5]
 [ 8 11  5]]
----------
[ 6  7  8  9 10 11 12  7  8  9 10 11 12]


ValueError: invalid literal for int() with base 10: 'True'