In [1]:
import numpy as np

# 1. Generating Random Numbers

In [2]:
print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.6851705076506323
[0.75903537 0.56181485 0.45676017]
9
[[5 4 1 9 0]
 [4 3 1 7 7]
 [0 2 9 6 3]]


# 2. Random Numbers with Seed

In [3]:
# np.random.seed(seed): Sets global random seed for REPRODUCIBLE results - SAME sequence every run
# Parameters: integer seed value (e.g., 2) - **CRITICAL for ML debugging and testing**
# Speed: O(1) operation - just resets internal state, no number generation
np.random.seed(2)

# ALWAYS same output after seed(2): 0.37454011884736244 ∈ [0, 1)
print(np.random.rand())             

# ALWAYS same 1D array after seed(2): [0.95071431 0.73199394 0.59865848]
print(np.random.rand(3))            

# ALWAYS same int after previous calls: 7 ∈ [0, 10)
print(np.random.randint(10))        

# ALWAYS same 3×5 matrix after previous calls - perfect for reproducible testing
print(np.random.randint(10, size=(3, 5)))

0.43599490214200376
[0.02592623 0.54966248 0.43532239]
8
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


In [4]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.22199317108973948
[0.87073231 0.20671916 0.91861091]
8
[[4 7 0 0 7]
 [1 5 7 0 1]
 [4 6 2 9 9]]


In [5]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.22199317108973948
[0.87073231 0.20671916 0.91861091]
8
[[4 7 0 0 7]
 [1 5 7 0 1]
 [4 6 2 9 9]]


# 3. Seed in Loops

In [7]:
np.random.seed(5)  # Set seed for reproducible results - same sequence every run

for i in range(10):
  arr = np.random.randint(2, size=1000)  # Generate 1000 binary ints (0 or 1) ∈ [0, 2)
  print(len(arr[arr == 1]) , len(arr[arr == 0]))  # Count 1s and 0s in array

505 495
509 491
481 519
508 492
510 490
490 510
503 497
475 525
496 504
499 501
