In [1]:
import numpy as np

# 1. Flattening

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

flat_arr = arr.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# 2. Reshaping

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr.shape)
print('-'*10)

reshaped_arr = np.reshape(arr, (3,2))
print(reshaped_arr)

print(reshaped_arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
----------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


# 3. Splitting

- vsplit

In [4]:
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)
print('-'*10)

for _ in np.vsplit(arr, 4):
  print(_)

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[[1 2 3 2]]
[[4 5 6 2]]
[[7 8 9 2]]
[[7 8 9 2]]


- hsplit

In [5]:
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)
print('-'*10)

print(np.hsplit(arr,4))

for _ in np.hsplit(arr, 4):
  print(_)

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[array([[1],
       [4],
       [7],
       [7]]), array([[2],
       [5],
       [8],
       [8]]), array([[3],
       [6],
       [9],
       [9]]), array([[2],
       [2],
       [2],
       [2]])]
[[1]
 [4]
 [7]
 [7]]
[[2]
 [5]
 [8]
 [8]]
[[3]
 [6]
 [9]
 [9]]
[[2]
 [2]
 [2]
 [2]]


- split

In [7]:
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)

print('-'*10)

split_arr = np.split(arr, 2, axis = 1)
print(split_arr)

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[array([[1, 2],
       [4, 5],
       [7, 8],
       [7, 8]]), array([[3, 2],
       [6, 2],
       [9, 2],
       [9, 2]])]


# 4. Merging

- concatenate

In [9]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.concatenate((arr1,arr2,arr3, arr4))

print(concat_arr)

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]


- hstack

In [10]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.hstack((arr1,arr2,arr3,arr4))

print(concat_arr)

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]


- vstack

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.vstack((arr1,arr2,arr3,arr4))

print(concat_arr)

[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


- stack

In [12]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.stack((arr1,arr2,arr3,arr4), axis = 0)

print(concat_arr)

[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


In [13]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.stack((arr1,arr2,arr3,arr4), axis = 1)

print(concat_arr)

[[1 1 9 8]
 [2 5 2 2]
 [3 2 3 9]
 [4 9 5 4]]
