In [1]:
import numpy as np

# 1. Zeros

In [6]:
#Create a 1D array of 10 zeros (shape: (10,))
zeros_array = np.zeros(10)
print(zeros_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# Create a 2D array (matrix) of 2 rows and 4 columns, all zeros (shape: (2, 4))
zeros_array = np.zeros((2, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Create a 3D array with shape (2, 3, 4) - think of it as 2 matrices of 3x4
zeros_array = np.zeros((2, 3, 4))
print(zeros_array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
# Create a 2D integer array (2x3) instead of default float64
zeros_array = np.zeros((2, 3), dtype=int)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


# 2. One

In [11]:
# Create a 1D array of 10 ones (shape: (10,))
# Default dtype is float64
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
# Create a 2D array (matrix) of 2 rows and 4 columns, all ones (shape: (2, 4))
ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Create a 3D array with shape (2, 3, 4) - 2 blocks of 3x4 matrices of ones
ones_array = np.ones((2, 3, 4))
print(ones_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [14]:
# Create a 2D integer array (2x3) filled with ones (explicit int dtype)
ones_array = np.ones((2, 3), dtype=int)
print(ones_array)

[[1 1 1]
 [1 1 1]]


# 3. Eye

In [15]:
# Create 3x3 Identity matrix (square diagonal matrix)
# Diagonal = 1s, off-diagonal = 0s (shape: (3, 3))
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Create 3x4 Identity-like matrix (rectangular)
# 3 rows, 4 columns - diagonal 1s up to min(3,4)=3, rest 0s (shape: (3, 4))
eye_array = np.eye(3, 4)
print(eye_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [17]:
# Create 3x4 Identity matrix with integer dtype instead of float64
eye_array = np.eye(3, 4, dtype=int)
print(eye_array)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


# 4. Random Number Generation

In [20]:
# np.random.rand(d0, d1, ..., dn): Returns array of random floats from uniform distribution [0, 1)
# Parameters: 
# - Shape arguments (like np.zeros): ()=scalar, (N)=1D array, (M,N)=2D matrix, etc.
# - Range is ALWAYS fixed [0, 1) - no low/high parameters needed
print(np.random.rand())           # Scalar: single random float ∈ [0, 1)
print(np.random.rand(10))         # 1D array: 10 random floats ∈ [0, 1)
print(np.random.rand(3, 3))       # 2D array: 3×3 matrix of random floats ∈ [0, 1)

0.009866966110309017
[0.29325385 0.37917006 0.3403139  0.99749506 0.18722614 0.48503746
 0.38624456 0.48881036 0.76799392 0.78249225]
[[0.29220787 0.80691941 0.9989927 ]
 [0.17152844 0.17367046 0.76496751]
 [0.95182618 0.41371406 0.35544084]]


In [21]:
# np.random.randint(low, high, size, dtype): Returns random integers from [low, high) range
# Parameters: 
# - low: inclusive lower bound (default=0)
# - high: exclusive upper bound 
# - size: output shape (scalar if omitted)
# - dtype: data type (default=int64)
print(np.random.randint(100))                    # Scalar: single int ∈ [0, 100)
print(np.random.randint(100, size=10))           # 1D array: 10 ints ∈ [0, 100)
print(np.random.randint(100, size=(3, 3)))       # 2D array: 3×3 matrix ∈ [0, 100)
print(np.random.randint(low=100, high=200, size=(3, 3)))  # 2D array: 3×3 matrix ∈ [100, 200)

42
[85 14 69 35 25 59 73 57 98 32]
[[25 83 40]
 [37 45 95]
 [46 35 44]]
[[171 187 126]
 [148 167 199]
 [118 156 115]]


In [22]:
# np.random.randn(d0, d1, ..., dn): Returns random floats from standard normal distribution (Gaussian)
# Parameters: 
# - Shape arguments (like np.zeros): ()=scalar, (N)=1D array, (M,N)=2D matrix, etc.
# - Mean = 0, Standard Deviation = 1 (standard normal), bell-shaped curve centered at 0
print(np.random.randn())         # Scalar: single random float ∼ N(0,1) (can be negative/positive)

0.3419766379194346


In [23]:
# np.random.uniform(low, high, size): Returns random floats from uniform distribution [low, high)
# Parameters: 
# - low: inclusive lower bound (default=0.0)
# - high: exclusive upper bound (default=1.0) 
# - size: output shape (scalar, array, matrix, etc.)
print(np.random.uniform(size=(3, 3)))    # 2D array: 3×3 matrix ∈ [0, 1)

[[0.73312541 0.98861767 0.7220927 ]
 [0.60012237 0.64914354 0.81864309]
 [0.69138816 0.72858715 0.15423251]]


In [24]:
# np.random.binomial(n, p, size): Returns random integers from binomial distribution B(n,p)
# Parameters: 
# - n: number of trials (fixed)
# - p: success probability per trial (0≤p≤1)
# - size: output shape (scalar, array, matrix, etc.)
print(np.random.binomial(10, 0.5, size=(3, 3)))    # 2D array: 3×3 matrix ∼ Binomial(n=10, p=0.5)

[[6 6 5]
 [3 6 4]
 [6 7 3]]


In [25]:
# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace