# 1. range

In [1]:
# The range() function creates an immutable sequence of numbers.
# Syntax: range(stop) or range(start, stop) or range(start, stop, step)
# - start: beginning number (default: 0, inclusive)
# - stop: end number (exclusive - never included in the sequence)
# - step: increment/decrement (default: 1, can be positive or negative)
# Returns a memory-efficient range object (not a list).

# Example 1: range(10) - defaults to range(0, 10, 1)
# Generates numbers from 0 up to (but not including) 10
r = range(10)
print(r)  # Output: range(0, 10)

# Example 2: range(0, 10, 2) - explicit start, positive step
# Generates even numbers: 0, 2, 4, 6, 8 (stops before 10)
r = range(0, 10, 2)
print(r)  # Output: range(0, 10, 2)

# Example 3: range(10, 0, -2) - start > stop, negative step
# Counts down even numbers: 10, 8, 6, 4, 2 (stops before 0)
r = range(10, 0, -2)
print(r)  # Output: range(10, 0, -2)

# Membership test: 'in' works efficiently on range objects
print(6 in range(10))  # Output: True (6 is between 0 and 9)

# Convert to list: range is iterable, list() materializes the sequence
print(list(range(10)))  # Output: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


range(0, 10)
range(0, 10, 2)
range(10, 0, -2)
True
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# 2. arange

In [2]:
import numpy as np

# np.arange() generates NumPy arrays filled with evenly spaced values.
# Syntax: np.arange(start, stop, step, dtype=None)
# - start: beginning value (default: 0, inclusive)
# - stop: end value (exclusive - never included)
# - step: spacing between values (default: 1.0, can be float/negative)
# Returns a NumPy ndarray (concrete array in memory, unlike range()).

# Example 1: Integer step - even numbers from 0 to <10
# Creates [0, 2, 4, 6, 8] as a NumPy array
arr = np.arange(0, 10, 2)
print(arr)  # Output: [0 2 4 6 8]

# Example 2: Negative step - countdown from 10 to >0  
# Creates [10, 9, 8, ..., 1] (stops before/at 0)
arr = np.arange(10, 0, -1)
print(arr)  # Output: [10  9  8  7  6  5  4  3  2  1]

# Example 3: Float step - generates values spaced by 0.5
# Creates [0. , 0.5, 1. , ..., 9.5] (stops before 10)
arr = np.arange(0, 10, 0.5)
print(arr)  # Output: [0.  0.5 1.  1.5 2.  2.5 ... 8.5 9.  9.5]

[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


# 3. linspace

In [3]:
import numpy as np

# np.linspace() generates evenly spaced numbers over a specified interval.
# Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# - start: beginning value (inclusive)
# - stop: end value (inclusive if endpoint=True, exclusive if False)
# - num: number of samples to generate (must be integer >=1)
# - endpoint: if True (default), stop is the last sample
# - retstep: if True, returns (samples, step_size) tuple
# Returns NumPy ndarray(s) with fixed number of points.

# Example 1: 5 evenly spaced points from 0 to 10 (inclusive)
# Divides interval into 4 segments, step ≈ 2.5
l = np.linspace(0, 10, 5)
print(l)  # Output: [ 0.   2.5  5.   7.5 10. ]

# Example 2: 10 points from 1 to 10 (inclusive), step ≈ 1.0
l = np.linspace(1, 10, 10)
print(l)  # Output: [ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10. ]

# Example 3: 10 points from 1 to 10 (endpoint=False), step ≈ 0.9
# Stop is exclusive, so last point before 10
l = np.linspace(1, 10, 10, endpoint=False)
print(l)  # Output: [1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]

# Example 4: Return both samples and step size
# l: 10 points from 1 to 5, s: calculated step (0.444...)
l, s = np.linspace(1, 5, 10, retstep=True)
print(l)  # Output: [1.   1.444... 1.888... 2.333... 2.777... 3.222... 3.666... 4.111... 4.555... 5.   ]
print(s)  # Output: 0.4444444444444444

[ 0.   2.5  5.   7.5 10. ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
0.4444444444444444


# 4. logspace

In [4]:
import numpy as np

# np.logspace() generates numbers spaced evenly on a logarithmic scale.
# Syntax: np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
# - start: exponent of first value (base**start)
# - stop: exponent of last value (base**stop if endpoint=True)
# - num: number of samples (>=1)
# - endpoint: include stop value (default True)
# - base: logarithmic base (default 10)
# Returns ndarray with log-spaced values.

# Example 1: 5 points, base=10, exponents 0 to 10 (inclusive)
# Values: 10^0, 10^2, 10^4, 10^6, 10^10
arr = np.logspace(0, 10, 5)
print(arr)  # Output: [1.e+00 1.e+02 1.e+04 1.e+06 1.e+10]

# Example 2: endpoint=False, so last value at 10^(10*(4/5)) = 10^8
# Values: 10^0, 10^2, 10^4, 10^6, 10^8
arr = np.logspace(0, 10, 5, endpoint=False)
print(arr)  # Output: [1.e+00 1.e+02 1.e+04 1.e+06 1.e+08]

# Example 3: base=2, exponents 0 to 10
# Values: 2^0, 2^2, 2^4, 2^6, 2^10
arr = np.logspace(0, 10, 5, base=2)
print(arr)  # Output: [  1.   4.  16.  64. 1024.]

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]
