In [1]:
import numpy as np

`1. reading from .txt`

In [5]:
data = np.loadtxt('data.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


`2. reading from .npy`

In [6]:
data = np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


`3. reading from .csv`

In [14]:
data = np.loadtxt('data.csv', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
data = np.loadtxt('data.json', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
data = np.loadtxt('data.yaml', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]
