In [2]:
import numpy as np

# 1. Creating Multidimensional Arrays

`1.1) Create a 2D array from a list of lists`

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


`1.2) Create a 3D array from a list of lists`

# 2. Finding details of an Array

In [4]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
