In [1]:
import numpy as np

# 1. Indexing and Slicing in Lists

In [19]:
my_list = [1, 2, 3, 4, 5]
print(my_list[0])
print(my_list[-1])
print(my_list[2])
print(my_list[1:4])
print(my_list[:3])
print(my_list[3:])
print(my_list[::2])
print(my_list[::-1])

my_list[0] = 10
print(my_list)

del my_list[1]
print(my_list)

my_list[1:1] = [20, 30]
print(my_list)

1
5
3
[2, 3, 4]
[1, 2, 3]
[4, 5]
[1, 3, 5]
[5, 4, 3, 2, 1]
[10, 2, 3, 4, 5]
[10, 3, 4, 5]
[10, 20, 30, 3, 4, 5]


# 2. Indexing and Slicing in Arrays

In [25]:
my_array = np.array([1, 2, 3, 4, 5])

print(my_array[0])
print(my_array[-1])
print(my_array[2])

print(my_array[1:4])
print(my_array[:3])
print(my_array[3:])
print(my_array[::2])
print(my_array[::-1])

my_array[0] = 10
print(my_array)

np.delete(my_array, 1)
print(my_array)

np.insert(my_array, 1, [20, 30])
print(my_array)

1
5
3
[2 3 4]
[1 2 3]
[4 5]
[1 3 5]
[5 4 3 2 1]
[10  2  3  4  5]
[10  2  3  4  5]
[10  2  3  4  5]
